### ISSUE TITLE
Idea. Make Copycat join Voice channels.

### ISSUE THREAD

**Issue by Giffel96** [Wiildanimal/Copycat#1]
Can we get a command to make copycat join and leave voice channels? 

It would be really useful for making other bots join the voice channel copycat is in. For an example:
Im using FredBoat♪♪ and copycat on my server right now. I would love for me to be able to write "copycat -join30 (channelID) say -s -d -cid (channelID) ;;play (link)". So copycat would join a specific voice channel (and stay there for 30 secs) and then Fredboat would follow it and play music. That way, i dont have to be in the voice channel, that i want Fredboat to play music in.

Anyways, it might only be me who would use that kinda thing, but i thought it would open up copycat to some more options.

**Comment by Arraying** [comment]
Sorry for the late reply.

This isn't something I'd be looking into adding at this moment, but I could look into it into the distant future.
